.MODEL SMALL
.STACK 100
.DATA
    MSG1 DB "WELCOME TO ASSEMBLY PROGRAMMING$"
.CODE
MAIN PROC
       MOV AX, @DATA  ; DATA ADDRESS IN AX REGISTER
       MOV DS, AX     ; STORING ADDRESS IN DS REGISTER
       
                      ; PRINT FUNCTION
       LEA DX, MSG1   ; LOAD MSG IN LOAD EFFECTIVE ADDRESS
       MOV AH, 9H      ; MOVING 9 IN AH, WHERE 9 IS A INTERRUPT FUNTION FOR SHOWING STRING 
       INT 21H        ; INTERRUPT 21H USED FOR DISPLAYING DATA
       
       MOV AH, 4CH    ; THIS IS FOR EXIT
       INT 21H
    MAIN ENDP
END MAIN




